#kubectl apply -f app-books-deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-app-orden-compra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-app-orden-compra
  template:
    metadata:
      labels:
        app: app-app-orden-compra
    spec:
      containers:
        - name: app-app-orden-compra
          image: dennisyaj/app-orden-compra
          env:
            - name: APP_CLIENTE_URL
              value: http://app-cliente-service:8080
            - name: APP_PRODUCTO_URL
              value: http://app-producto-service:8080
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: app-app-orden-compra-service
spec:
  type: ClusterIP
  selector:
    app: app-app-orden-compra
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
